#!/usr/bin/env ruby

# ./run-test runs everything
# ./run-test /Class/ runs a file's worth of tests.
# ./run-test /test/ runs a specific test

# make sure we get the development version.
$:.unshift '..', '../fluid', '../ruby-trace'  
require 'timeclock/util/misc'
require 'timeclock/util/Configuration'
require 'ServerManager'

# On Windows, you'll need something like this:
# ENV["VW_TIMECLOCK_DATA_DIR"] = "/temp/timeclockdatadir"
# The following line will fail if it's not set.
Timeclock::Configuration.ensure_data_dir
Timeclock::Configuration.start_log('product-test.txt', 'debug')

if ARGV[0] == "--quiet"
  ARGV.shift
else
  Todo.enable_printing
end

ENV["VW_TIMECLOCK_HOST"] = "localhost"
ENV["VW_TIMECLOCK_PORT"] = "21960"


ServerManager.connect
at_exit {
  ServerManager.stop_server
}

# Note that the following require must follow the preceding
# at_exit. Test::unit installs an at_exit testrunner that runs
# the tests. Then the preceding will shut down the server.

require 'test/unit'


# Use this to exclude particular files during development.
class Excluded

  attr_accessor :files
  def initialize(files)
    @files = files
  end

  def empty?
    @files.empty?
  end

  def omit?(name)
    @files.find { | e | e == name }
  end
end

excluded = Excluded.new([])

Dir["*.rb"].each { | name | 
  require name unless excluded.omit?(name)
}
if not excluded.empty?
  puts "!!!!!!!!!!!!  excluding the following:"
  puts excluded.files
  puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
end
