#!/usr/bin/env ruby
require 'test/unit'

# make sure we get the development version.
$:.unshift '..', '../fluid', '../ruby-trace'  
require 'timeclock/util/misc'
require 'timeclock/util/Configuration'

if ARGV[0] == "--quiet"
  ARGV.shift
else
  Todo.enable_printing
end

if ARGV[0] == "--verbose"
  $show_names = true
  ARGV.shift
end

# On Windows, you'll need something like this:
# ENV["VW_TIMECLOCK_DATA_DIR"] = "/temp/timeclockdatadir"
# The following line will fail if it's not set.
Timeclock::Configuration.ensure_data_dir
Timeclock::Configuration.start_log('unit-test.txt', 'debug')

def test_require (name)
  return if name == "util/tConfiguration.rb" # see note in this file
  puts name if $show_names 
  require name
end

if ARGV[0] and ARGV[0] =~ /\.rb$/
  require ARGV[0]
  ARGV.shift
else
  Dir["*/t*.rb"].each { | name | test_require name } 
  Dir["*/*/t*.rb"].each { | name | test_require name }
end

