require 'rubygems'
require 'hoe'
require './lib/commonwatir.rb'

Hoe.new('commonwatir', CommonWatir::VERSION) do |p|
  p.rubyforge_name = 'wtr'
  p.developer('Bret Pettichord', 'bret@pettichord.com')
  p.extra_deps << ['user-choices', '>= 0']
  p.url = 'http://www.watir.com'
end