require 'rubygems'
require 'hoe'
require './lib/commonwatir.rb'

Hoe.new('commonwatir', CommonWatir::VERSION) do |p|
  p.rubyforge_name = 'wtr'
  p.developer('Bret Pettichord', 'bret@watircraft.com')
  p.extra_deps << 'user-choices'
end
