require 'rubygems'
require 'hoe'
require './lib/commonwatir.rb'

Hoe.spec 'commonwatir' do
  self.version = CommonWatir::VERSION
  self.rubyforge_name = 'wtr'
  self.developer('Bret Pettichord', 'bret@pettichord.com')
  self.extra_deps << ['user-choices', '>= 0']
  self.url = 'http://www.watir.com'
end