require 'watir-classic/version'
require 'watir-classic/wait'
require 'watir-classic/wait_helper'
require 'watir-classic/element_extensions'
require 'watir-classic/util'
require 'watir-classic/exceptions'
require 'watir-classic/matches'
require 'watir-classic/browser'
