all: clean
	@echo "-----> One test in LogfileDestination_backup is known to be broken."
	@echo "-----> I suspect a Ruby bug."
	ruby -I.. All.rb

clean:
	rm -f out-* [a-z]*-example.rb usage-example-?.rb todo-example-?.rb
